# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171029_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
